package com.acesoft.leetcode;

/*
 * https://leetcode.com/problems/find-the-difference
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random
 * position.
 *
 * Return the letter that was added to t.
 *
 * Example 1:
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 *
 * Example 2:
 * Input: s = "", t = "y"
 * Output: "y"
 *
 * Constraints:
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 */
public class LeetCode389 {

  public char findTheDifference(String s, String t) {
    int[] alphabets = new int[26];
    int i;
    for (char ch : s.toCharArray()) {
      alphabets[ch - 'a']++;
    }
    for (char ch : t.toCharArray()) {
      alphabets[ch - 'a']--;
    }
    for (i = 0; i < 26; i++) {
      if (alphabets[i] < 0) {
        break;
      }
    }
    return (char) (97 + i);
  }
}
